export interface JobListing {
  id?: string; // Optional because it's generated by DB
  platform: string;
  external_id: string;
  title: string;
  description: string | null;
  url: string | null;
  hourly_rate_min: number | null;
  hourly_rate_max: number | null;
  fixed_price: number | null;
  client_payment_verified: boolean | null;
  client_total_spent: number | null;
  client_country: string | null;
  skills: string[] | null;
  raw: any; // Using any to store original JSON payload
  posted_at: string | null; // Keep as string for transport, DB handles conversion usually
  fetched_at?: string;
}

export type JobListingInsert = Omit<JobListing, 'id' | 'fetched_at'>;
